name: Ploomber CI
description: Make sure your Data Science pipeline is reproducible by automatically running it each time you push to your repository.

branding:
  icon: book-open
  color: gray-dark

inputs:
  path:
    description: Relative path in the repo to move before executing the action
    required: false
    default: .

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}