name: Ploomber CI
description: Automatically run Jupyter notebook pipelines on each push to ensure reproducibility

branding:
  icon: book-open
  color: gray-dark

inputs:
  path:
    description: Relative path in the repo to move before executing the action
    required: false
    default: .

runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}